name: mymavenbuild
on: push

jobs:
  installmaven:
    runs-on: self-hosted
    # permissions: 
    #     content: read
    #     package: write

    steps:
      - name: setup java and maven
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           cache: 'maven'